import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    paddingTop: 20,
    flex: 1,
    backgroundColor: '#3A8FB7',
  },
  rowContainer: {
    flex: 1,
    alignItems: 'stretch',
    padding: 15,
    flexDirection: 'column',
    marginTop: 15,
    backgroundColor: 'white',
  },
  buttonContainer: {
    flexDirection: 'column',
    flex: 1,
    alignItems: 'stretch',
    marginBottom: 10,
    paddingTop: 5,
    width: '100%',
  },
  text: {
    paddingTop: 16,
    paddingLeft: 10,
    textAlign: 'center',
    marginVertical: '60%',
    marginHorizontal: 5,
    color: '#3A8FB7',
    fontFamily: 'Avenir',
    fontSize: 22,
  },
  input: {
    height: 150,
    paddingVertical: 6,
    paddingHorizontal: 10,
    margin: 10,
    borderColor: '#3A8FB7',
    borderWidth: 1.7,
    borderRadius: 10,
    color: 'black',
    fontFamily: 'Avenir',
    fontSize: 18,
  },
  textContainer: {
    padding: '5%',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  listContainer: {
    flex: 1,
    padding: 0,
    paddingTop: 0,
    justifyContent: 'space-around',
    backgroundColor: 'white',
  },
  list: {
    flex: 1,
  },
  noDisplay: {
    display: 'none',
  },
  OverlayContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(110, 117, 112, 0.5)',
  },
  activityIndicatorContainer: {
    width: 180,
    height: 120,
    backgroundColor: 'white',
    borderRadius: 5,
    position: 'absolute',
    top: 200,
  },
  activityIndicator: {
    width: 50,
    height: 50,
    alignSelf: 'center',
    position: 'absolute',
    top: 10,
  },
  activityIndicatorText: {
    textAlign: 'center',
    color: '#3A8FB7',
    fontFamily: 'Avenir',
    fontSize: 16,
  },
})
